services:
  install-backend:
    image: node:22-alpine
    working_dir: /var/workspace
    volumes:
      - ./backend:/var/workspace
    command: ["npm", "install", "--no-save", "--silent"]
  backend:
    image: node:22-alpine
    working_dir: /var/workspace
    volumes:
      - ./backend:/var/workspace
    command: ["npm", "run", "dev"]
    healthcheck:
      interval: 1s
      test: ["CMD-SHELL",
             "node", "-c",
             "node --input-type=module -e \"process.exit((await fetch('http://backend:8080/api/healthcheck')).ok === true ? 0 : 1)\""]
    depends_on:
      install-backend:
        condition: service_completed_successfully

  install-webapp:
    image: node:22-alpine
    working_dir: /var/workspace
    volumes:
      - ./webapp:/var/workspace
    command: ["npm", "install", "--no-save", "--silent"]
  webapp:
    image: node:22-alpine
    working_dir: /var/workspace
    volumes:
      - ./webapp:/var/workspace
    command: ["npm", "run", "dev", "--", "--host", "webapp"]
    healthcheck:
      interval: 1s
      test: ["CMD-SHELL",
             "node", "-c",
             "node --input-type=module -e \"process.exit((await fetch('http://webapp:5173')).ok === true ? 0 : 1)\""]
    depends_on:
      backend:
        condition: service_healthy
      install-webapp:
        condition: service_completed_successfully

  reverse-proxy:
    image: nginx:1.27
    volumes:
      - ./docker/provisioning/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
      webapp:
        condition: service_healthy
